#define DEBUG_TOKEN_PASTE(x) DEBUG_##x
#define DEBUG_ENABLED(f) DEBUG_TOKEN_PASTE(f)>DISABLED
#define DEBUG_DebuggerMain DISABLED
#define DEBUG_CpuApStart DISABLED
#define DEBUG_krn_MmuUnmapPage DISABLED
#define DEBUG_krn_MmuMapPage DISABLED
#define DEBUG_AcpiFindRsdp DISABLED
#define DEBUG_AcpiCheckTable DISABLED
#define DEBUG_AcpiReadXsdt DISABLED
#define DEBUG_AcpiReadRsdt DISABLED
#define DEBUG_AcpiGetTableSig DISABLED
#define DEBUG_AcpiReadMadt DISABLED
#define DEBUG_lInit DISABLED
#define DEBUG_MBootGetKernel DISABLED
#define DEBUG_MBootGetMb1Kernel DISABLED
#define DBEUG_MBootGetKernel DISABLED
#define DEBUG_GetPML4Entry DISABLED
#define DEBUG_GetPDPTEntry DISABLED
#define DEBUG_GetPDEntry DISABLED
#define DEBUG_GetPTEntry DISABLED
#define DEBUG_MmuIsMapped DISABLED
#define DEBUG_ldr_MmuMapPage DISABLED
#define DEBUG_ldr_MmuUnmapPage DISABLED
#define DEBUG_MmuEmptyPdpt DISABLED
#define DEBUG_pmm_LateInit DISABLED
#define DEBUG_PmmCleanProcess DISABLED
#define DEBUG_pmm_PmmReleaseFrame DISABLED
#define DEBUG_pmm_PmmAllocateAligned DISABLED
#define DEBUG_pmm_DoAllocAlignedFrames DISABLED
#define DEBUG_PmmAllocate DISABLED
#define DEBUG_PmmInitEarly DISABLED
#define DEBUG_PmmDoRemoveFrame DISABLED
#define DEBUG_PmmScrubFrame DISABLED
